package com.mcsoftware.atm.constant;

public enum EFeeCategory {
    MICRO_DEPOSIT,MICRO_TRANSFER,MICRO_WITHDRAWAL,
    STANDARD_DEPOSIT,STANDARD_TRANSFER,STANDARD_WITHDRAWAL,
    EXCESSIVE_DEPOSIT,EXCESSIVE_TRANSFER,EXCESSIVE_WITHDRAWAL
}
